name: boilerplate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.7.0 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  dio: ^5.8.0+1
  intl: any
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  connection_notifier: ^2.0.1
  carousel_slider: ^5.0.0
  another_flushbar: ^1.12.30
  smooth_page_indicator: ^1.2.1
  persistent_bottom_nav_bar: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  syncfusion_flutter_pdfviewer: ^28.2.7
  custom_refresh_indicator: ^4.0.1
  syncfusion_flutter_charts: ^28.2.7
  webview_flutter: ^4.10.0
  buttons_tabbar: ^1.3.15
  loader_overlay: ^5.0.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  fl_chart: ^0.70.2
  gap: ^3.0.1
  package_info_plus: ^8.3.0
  upgrader: ^11.3.1
  device_info_plus: ^11.3.3
  intl_phone_field: ^3.2.0
  flutter_facebook_auth: ^7.1.1
  otp_pin_field: ^1.4.0
  flutter_local_notifications: ^18.0.1

  # Icons
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2


  #State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5


  # Payment Gateway
  flutter_bkash: ^0.2.0
  flutter_stripe: ^11.4.0
  flutter_sslcommerz: ^2.4.1
  cached_network_image: ^3.4.1









dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - .env


  # Local Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         styles: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
